[package]
name = "toml"
version = "0.1.0"
kern = "0.7"
publish = false

[lib]
root = "src/lib.rn"

[[test]]
name = "parse_smoke"
root = "tests/parse_smoke.rn"

[[test]]
name = "parse_errors"
root = "tests/parse_errors.rn"
