use super::AnalysisContext;
use std::collections::BTreeMap;

pub(super) fn compile_time_values(
    cfg: &BTreeMap<String, crate::plan::PlanValue>,
    define: &BTreeMap<String, crate::plan::PlanValue>,
) -> BTreeMap<String, String> {
    let mut values = BTreeMap::new();
    for (name, value) in cfg {
        values.insert(name.clone(), plan_value_string(value));
    }
    for (name, value) in define {
        values.insert(name.clone(), plan_value_string(value));
    }
    values
}

fn plan_value_string(value: &crate::plan::PlanValue) -> String {
    match value {
        crate::plan::PlanValue::Bool(value) => value.to_string(),
        crate::plan::PlanValue::String(value) => value.clone(),
    }
}

impl AnalysisContext {
    pub(super) fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is generated by craft.\n");
        out.push_str("version = ");
        out.push_str(&self.version.to_string());
        out.push('\n');
        push_string_line(&mut out, "manifest", &self.manifest);
        push_string_line(&mut out, "manifest-digest", &self.manifest_digest);
        push_string_line(&mut out, "profile", &self.profile);
        push_bool_line(&mut out, "default-features", self.default_features);
        push_string_array_line(&mut out, "features", &self.features);
        if let Some(path) = &self.workspace_script {
            push_string_line(&mut out, "workspace-script", path);
        }
        if let Some(digest) = &self.workspace_script_digest {
            push_string_line(&mut out, "workspace-script-digest", digest);
        }

        for package in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            push_string_line(&mut out, "manifest", &package.manifest);
            push_string_line(&mut out, "manifest-digest", &package.manifest_digest);
            if let Some(path) = &package.craft_script {
                push_string_line(&mut out, "craft-script", path);
            }
            if let Some(digest) = &package.craft_script_digest {
                push_string_line(&mut out, "craft-script-digest", digest);
            }
        }

        for unit in &self.units {
            out.push('\n');
            out.push_str("[[unit]]\n");
            push_string_line(&mut out, "manifest", &unit.manifest);
            push_string_line(&mut out, "source-root", &unit.source_root);
            push_string_line(&mut out, "target-kind", &unit.target_kind);
        }

        for alias in &self.unit_aliases {
            out.push('\n');
            out.push_str("[[unit-alias]]\n");
            push_string_line(&mut out, "manifest", &alias.manifest);
            push_string_line(&mut out, "source-root", &alias.source_root);
            push_string_line(&mut out, "source-path", &alias.source_path);
            push_string_line(&mut out, "generated-path", &alias.generated_path);
        }

        for value in &self.unit_values {
            out.push('\n');
            out.push_str("[[unit-value]]\n");
            push_string_line(&mut out, "manifest", &value.manifest);
            push_string_line(&mut out, "source-root", &value.source_root);
            push_string_line(&mut out, "name", &value.name);
            push_string_line(&mut out, "value", &value.value);
        }

        out
    }
}

fn push_bool_line(out: &mut String, key: &str, value: bool) {
    out.push_str(key);
    out.push_str(" = ");
    out.push_str(if value { "true" } else { "false" });
    out.push('\n');
}

fn push_string_line(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = \"");
    out.push_str(&escape_string(value));
    out.push_str("\"\n");
}

fn push_string_array_line(out: &mut String, key: &str, values: &[String]) {
    out.push_str(key);
    out.push_str(" = [");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push('"');
        out.push_str(&escape_string(value));
        out.push('"');
    }
    out.push_str("]\n");
}

fn escape_string(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}
