[package]
name = "std"
version = "0.7.6"
kern = "0.7.6"
description = "User-facing Kern standard library"
readme = "README.md"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]

[runtime]
entry = "none"
libc = false
bundle = "std"

[lib]
root = "mod.kn"

[dependencies]
base = { workspace = true }
