use crate::error::{Error, Result};
use crate::graph::{DependencyKind, DependencyTarget, PackageGraph, PackageId, SourceId};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u32,
    pub manifest: String,
    pub manifest_digest: String,
    pub packages: Vec<LockedPackage>,
    pub dependencies: Vec<LockedDependency>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    pub id: String,
    pub name: String,
    pub version: String,
    pub source_kind: &'static str,
    pub source_value: Option<String>,
    pub manifest: String,
    pub manifest_digest: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedDependency {
    pub from: String,
    pub kind: &'static str,
    pub name: String,
    pub package: String,
    pub target_kind: &'static str,
    pub target_value: Option<String>,
    pub target_id: Option<String>,
    pub version: Option<String>,
}

pub fn write_lockfile(manifest_path: &Path, graph: &PackageGraph) -> Result<PathBuf> {
    let lockfile = Lockfile::from_graph(manifest_path, graph)?;
    let lock_path = graph.workspace_root.join("Kraft.lock");
    fs::write(&lock_path, lockfile.render()).map_err(|err| Error::from_io(&lock_path, err))?;
    Ok(lock_path)
}

impl Lockfile {
    pub fn from_graph(manifest_path: &Path, graph: &PackageGraph) -> Result<Self> {
        let root = &graph.workspace_root;
        let manifest = relative_display(root, manifest_path);
        let manifest_digest = digest_file(manifest_path)?;

        let mut packages = Vec::new();
        let mut dependencies = Vec::new();

        for package in &graph.packages {
            let package_id = package_lock_id(&package.id);
            packages.push(LockedPackage {
                id: package_id.clone(),
                name: package.id.name.clone(),
                version: package.id.version.clone(),
                source_kind: source_kind(&package.id.source),
                source_value: source_value(&package.id.source),
                manifest: relative_display(root, &package.manifest_path),
                manifest_digest: digest_file(&package.manifest_path)?,
            });

            for dep in &package.dependencies {
                let (target_kind, target_value, target_id, version) = match &dep.target {
                    DependencyTarget::Local(target) => (
                        "local",
                        None,
                        Some(package_lock_id(target)),
                        Some(target.version.clone()),
                    ),
                    DependencyTarget::External(target) => (
                        source_kind(&target.source),
                        source_value(&target.source),
                        None,
                        target.version.clone(),
                    ),
                };

                dependencies.push(LockedDependency {
                    from: package_id.clone(),
                    kind: dependency_kind(dep.kind),
                    name: dep.dependency_name.clone(),
                    package: dep.package_name.clone(),
                    target_kind,
                    target_value,
                    target_id,
                    version,
                });
            }
        }

        Ok(Self {
            version: 1,
            manifest,
            manifest_digest,
            packages,
            dependencies,
        })
    }

    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is generated by kraft.\n");
        out.push_str("version = ");
        out.push_str(&self.version.to_string());
        out.push('\n');
        push_string_line(&mut out, "manifest", &self.manifest);
        push_string_line(&mut out, "manifest-digest", &self.manifest_digest);

        for package in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            push_string_line(&mut out, "id", &package.id);
            push_string_line(&mut out, "name", &package.name);
            push_string_line(&mut out, "version", &package.version);
            push_string_line(&mut out, "source", package.source_kind);
            if let Some(value) = &package.source_value {
                push_string_line(&mut out, "source-value", value);
            }
            push_string_line(&mut out, "manifest", &package.manifest);
            push_string_line(&mut out, "manifest-digest", &package.manifest_digest);
        }

        for dependency in &self.dependencies {
            out.push('\n');
            out.push_str("[[dependency]]\n");
            push_string_line(&mut out, "from", &dependency.from);
            push_string_line(&mut out, "kind", dependency.kind);
            push_string_line(&mut out, "name", &dependency.name);
            push_string_line(&mut out, "package", &dependency.package);
            push_string_line(&mut out, "target", dependency.target_kind);
            if let Some(value) = &dependency.target_value {
                push_string_line(&mut out, "target-value", value);
            }
            if let Some(target_id) = &dependency.target_id {
                push_string_line(&mut out, "target-id", target_id);
            }
            if let Some(version) = &dependency.version {
                push_string_line(&mut out, "version", version);
            }
        }

        out
    }
}

fn dependency_kind(kind: DependencyKind) -> &'static str {
    match kind {
        DependencyKind::Normal => "normal",
        DependencyKind::Dev => "dev",
        DependencyKind::Build => "build",
    }
}

fn package_lock_id(id: &PackageId) -> String {
    match &id.source {
        SourceId::Root => format!("{} {} root", id.name, id.version),
        SourceId::WorkspaceMember { path } => {
            format!("{} {} workspace-member:{path}", id.name, id.version)
        }
        SourceId::PathDependency { path } => {
            format!("{} {} path:{path}", id.name, id.version)
        }
        SourceId::Registry { name: Some(name) } => {
            format!("{} {} registry:{name}", id.name, id.version)
        }
        SourceId::Registry { name: None } => format!("{} {} registry", id.name, id.version),
    }
}

fn source_kind(source: &SourceId) -> &'static str {
    match source {
        SourceId::Root => "root",
        SourceId::WorkspaceMember { .. } => "workspace-member",
        SourceId::PathDependency { .. } => "path",
        SourceId::Registry { .. } => "registry",
    }
}

fn source_value(source: &SourceId) -> Option<String> {
    match source {
        SourceId::Root => None,
        SourceId::WorkspaceMember { path } => Some(path.clone()),
        SourceId::PathDependency { path } => Some(path.clone()),
        SourceId::Registry { name } => name.clone(),
    }
}

fn relative_display(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .map(|relative| relative.to_string_lossy().replace('\\', "/"))
        .unwrap_or_else(|_| path.to_string_lossy().replace('\\', "/"))
}

fn digest_file(path: &Path) -> Result<String> {
    let bytes = fs::read(path).map_err(|err| Error::from_io(path, err))?;
    Ok(format!("fnv1a64:{:016x}", fnv1a64(&bytes)))
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    const OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const PRIME: u64 = 0x100000001b3;

    let mut hash = OFFSET_BASIS;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}

fn push_string_line(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = \"");
    out.push_str(&escape_string(value));
    out.push_str("\"\n");
}

fn escape_string(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::{Lockfile, write_lockfile};
    use crate::graph::build_graph;
    use crate::manifest::Manifest;
    use crate::workspace::load_members;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_dir(prefix: &str) -> std::path::PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("{prefix}-{nanos}"));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn renders_workspace_lockfile_from_package_graph() {
        let root = temp_dir("kraft-lockfile");
        let app_dir = root.join("app");
        let util_dir = root.join("util");
        fs::create_dir_all(&app_dir).unwrap();
        fs::create_dir_all(&util_dir).unwrap();

        fs::write(
            root.join("Kraft.toml"),
            r#"
[workspace]
members = ["app", "util"]

[workspace.dependencies]
shared = "2"
"#,
        )
        .unwrap();
        fs::write(
            app_dir.join("Kraft.toml"),
            r#"
[package]
name = "app"
version = "0.1.0"
kern = "0.7"

[dependencies]
util = { path = "../util" }
shared = { workspace = true, features = ["simd"] }
"#,
        )
        .unwrap();
        fs::write(
            util_dir.join("Kraft.toml"),
            r#"
[package]
name = "util"
version = "0.1.0"
kern = "0.7"
"#,
        )
        .unwrap();

        let manifest_path = root.join("Kraft.toml");
        let root_manifest = Manifest::load(&manifest_path).unwrap();
        let members = load_members(&manifest_path, &root_manifest).unwrap();
        let graph = build_graph(&manifest_path, &root_manifest, &members).unwrap();
        let lockfile = Lockfile::from_graph(&manifest_path, &graph).unwrap();
        let rendered = lockfile.render();

        assert!(rendered.contains("version = 1"));
        assert!(rendered.contains("[[package]]"));
        assert!(rendered.contains("id = \"app 0.1.0 workspace-member:app\""));
        assert!(rendered.contains("target-id = \"util 0.1.0 workspace-member:util\""));
        assert!(rendered.contains("name = \"shared\""));
        assert!(rendered.contains("target = \"registry\""));
        assert!(rendered.contains("version = \"2\""));
        assert!(rendered.contains("manifest-digest = \"fnv1a64:"));

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn writes_lockfile_into_workspace_root() {
        let root = temp_dir("kraft-lockfile-write");
        let app_dir = root.join("app");
        fs::create_dir_all(&app_dir).unwrap();

        fs::write(
            root.join("Kraft.toml"),
            r#"
[workspace]
members = ["app"]
"#,
        )
        .unwrap();
        fs::write(
            app_dir.join("Kraft.toml"),
            r#"
[package]
name = "app"
version = "0.1.0"
kern = "0.7"
"#,
        )
        .unwrap();

        let manifest_path = root.join("Kraft.toml");
        let root_manifest = Manifest::load(&manifest_path).unwrap();
        let members = load_members(&manifest_path, &root_manifest).unwrap();
        let graph = build_graph(&manifest_path, &root_manifest, &members).unwrap();
        let lock_path = write_lockfile(&manifest_path, &graph).unwrap();
        let contents = fs::read_to_string(&lock_path).unwrap();

        assert_eq!(lock_path, root.join("Kraft.lock"));
        assert!(contents.contains("manifest = \"Kraft.toml\""));

        let _ = fs::remove_dir_all(root);
    }
}
