[package]
name = "rt"
version = "0.8.2"
kern = "0.8"
description = "Runtime startup glue and compiler-required fallbacks for Kern"
readme = "README.md"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]

[runtime]
entry = "none"
libc = false
bundle = "none"

[lib]
root = "lib.kn"
