[workspace]
name = "workspace"
members = [
    "base",
    "base-test",
    "prov",
    "std",
    "rt",
]

[workspace.package]
description = "Official Kern library workspace"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]
readme = "README.md"

[workspace.dependencies]
base = { path = "base" }
prov = { path = "prov" }
std = { path = "std" }
rt = { path = "rt" }
