[package]
name = "limine-smoke"
version = "0.1.0"
kern = "0.7"
description = "Small freestanding Limine smoke package for craft resource-flow testing"
readme = "README.md"
license = "MIT"

[runtime]
entry = "none"
libc = false
bundle = "base"

[[bin]]
name = "kernel"
root = "src/main.kn"

[build-dependencies]
mkiso = { path = "../limine-mkiso", export = "limine-mkiso" }

[resources]
limine = { git = "https://github.com/limine-bootloader/limine.git", tag = "v11.4.0-binary" }
