[package]
name = "kernlib-test"
version = "0.7.9"
kern = "0.7"
description = "Internal Kern tests for the official kernlib workspace"

[test]
roots = [
    "src/abi.kn",
    "src/alloc.kn",
    "src/coll_map.kn",
    "src/coll_seq.kn",
    "src/coll_tree.kn",
    "src/fs_io.kn",
    "src/fs_path.kn",
    "src/io.kn",
    "src/num.kn",
    "src/std_host.kn",
    "src/sync.kn",
    "src/test.kn",
    "src/text.kn",
]
