use super::Lockfile;

impl Lockfile {
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is generated by craft.\n");
        out.push_str("version = ");
        out.push_str(&self.version.to_string());
        out.push('\n');
        push_string_line(&mut out, "manifest", &self.manifest);
        push_string_line(&mut out, "manifest-digest", &self.manifest_digest);

        for package in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            push_string_line(&mut out, "id", &package.id);
            push_string_line(&mut out, "name", &package.name);
            push_string_line(&mut out, "version", &package.version);
            push_string_line(&mut out, "source", &package.source_kind);
            if let Some(value) = &package.source_value {
                push_string_line(&mut out, "source-value", value);
            }
            push_string_line(&mut out, "manifest", &package.manifest);
            push_string_line(&mut out, "manifest-digest", &package.manifest_digest);
        }

        for target in &self.package_targets {
            out.push('\n');
            out.push_str("[[package-target]]\n");
            push_string_line(&mut out, "package", &target.package_id);
            push_string_line(&mut out, "kind", &target.kind);
            if let Some(name) = &target.name {
                push_string_line(&mut out, "name", name);
            }
            push_string_line(&mut out, "root", &target.root);
        }

        for resource in &self.package_resources {
            out.push('\n');
            out.push_str("[[package-resource]]\n");
            push_string_line(&mut out, "package", &resource.package_id);
            push_string_line(&mut out, "name", &resource.name);
            push_string_line(&mut out, "source", &resource.source_kind);
            if let Some(value) = &resource.source_value {
                push_string_line(&mut out, "source-value", value);
            }
            if let Some(locator) = &resource.source_locator {
                push_string_line(&mut out, "source-locator", locator);
            }
            if let Some(selector) = &resource.source_selector {
                push_string_line(&mut out, "source-selector", selector);
            }
        }

        for package in &self.external_packages {
            out.push('\n');
            out.push_str("[[external-package]]\n");
            push_string_line(&mut out, "id", &package.id);
            push_string_line(&mut out, "name", &package.name);
            push_string_line(&mut out, "source", &package.source_kind);
            if let Some(value) = &package.source_value {
                push_string_line(&mut out, "source-value", value);
            }
            if let Some(version) = &package.version {
                push_string_line(&mut out, "version", version);
            }
            if let Some(locator) = &package.source_locator {
                push_string_line(&mut out, "source-locator", locator);
            }
            if let Some(selector) = &package.source_selector {
                push_string_line(&mut out, "source-selector", selector);
            }
        }

        for dependency in &self.dependencies {
            out.push('\n');
            out.push_str("[[dependency]]\n");
            push_string_line(&mut out, "from", &dependency.from);
            push_string_line(&mut out, "kind", &dependency.kind);
            push_string_line(&mut out, "name", &dependency.name);
            push_string_line(&mut out, "package", &dependency.package);
            push_string_line(&mut out, "target", &dependency.target_kind);
            push_string_line(&mut out, "target-id", &dependency.target_id);
        }

        for proof in &self.publish_proofs {
            out.push('\n');
            out.push_str("[[publish-proof]]\n");
            push_string_line(&mut out, "package-id", &proof.package_id);
            push_string_line(&mut out, "path", &proof.path);
            push_string_line(&mut out, "package", &proof.package);
            push_string_line(&mut out, "version", &proof.version);
            push_string_line(&mut out, "kern", &proof.kern);
            push_string_line(&mut out, "description", &proof.description);
            push_string_line(&mut out, "license", &proof.license);
            push_string_array_line(&mut out, "authors", &proof.authors);
            push_string_line(&mut out, "readme", &proof.readme);
            push_string_line(&mut out, "repository", &proof.repository);
            push_string_line(&mut out, "manifest-sha256", &proof.manifest_sha256);
            push_string_line(&mut out, "source-sha256", &proof.source_sha256);
        }

        out
    }
}

fn push_string_line(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = \"");
    out.push_str(&escape_string(value));
    out.push_str("\"\n");
}

fn push_string_array_line(out: &mut String, key: &str, values: &[String]) {
    out.push_str(key);
    out.push_str(" = [");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push('"');
        out.push_str(&escape_string(value));
        out.push('"');
    }
    out.push_str("]\n");
}

fn escape_string(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}
