[package]
name = "base"
version = "0.7.6"
kern = "0.7.6"
publish = false
description = "Freestanding primitives and data structures for Kern"
readme = "README.md"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]

[runtime]
entry = "none"
libc = false
bundle = "base"

[lib]
root = "init.rn"
